- name: Clone yay repository
  become: false
  tags:
    - yay
    - files
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/{{ ansible_user }}/yay  # Clone to the user's home directory
    update: no

- name: Build and install yay
  become: false
  tags:
    - yay
    - packages
  command: makepkg -si --noconfirm
  args:
    chdir: /home/{{ ansible_user }}/yay  # Change to the yay directory
