- name: (wallpapers) copy config files
  become: false
  tags:
    - wallpapers
    - files
  ansible.builtin.command:
    cmd: "cp -rf {{ role_path }}/files/wallpaper /home/{{ ansible_user }}/"

- name: (wallpapers) save config files
  become: false
  tags:
    - save
    - save-wallpapers
  ansible.builtin.command:
    cmd: "cp -rf /home/{{ ansible_user }}/wallpaper {{ role_path }}/files/"
