- name: (xorg) install packages
  tags:
    - xorg
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - xorg

- name: (xorg) copy xinitrc
  become: false
  tags:
    - xorg
    - files
  ansible.builtin.copy:
    src: .xinitrc
    dest: /home/{{ ansible_user }}/.xinitrc
    group: "users"
    owner: "{{ ansible_user }}"
    mode: 0755 # the owner of a file or directory can read, write, and execute it, while other users can only read and execute it

- name: (xorg) create conf.d directory
  become: true
  tags:
    - xorg
    - files
  ansible.builtin.file:
    path: "/etc/X11/xorg.conf.d"
    state: directory
    owner: "root"
    group: "root"

- name: (xorg) copy 30-touchpad.conf file
  become: true
  tags:
    - xorg
    - files
  ansible.builtin.copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    owner: "root"
    group: "root"
    mode: 0644 # the owner (root) can read and write the file, but other users can only read it

- name: (xorg) save xinitrc
  become: false
  tags:
    - save
    - save-xorg
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.xinitrc
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/xorg/files/.xinitrc
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0755 # the owner of a file or directory can read, write, and execute it, while other users can only read and execute it


