- name: (ssh) create ssh directory
  become: false
  tags:
    - ssh
    - files
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/.ssh"
    state: directory
    group: "users"
    owner: "{{ ansible_user }}"
    mode: 0700 # Only the owner can read, write, and execute (access) the directory

- name: (ssh) create public file
  become: false
  tags:
    - ssh
    - files
  ansible.builtin.copy:
    content: "{{ public_ssh_key_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519.pub"
    group: "users"
    owner: "{{ ansible_user }}"
    mode: 0644 # he owner can read and write the file, but other users can only read it

- name: (ssh) create private file
  become: false
  tags:
    - ssh
    - files
  ansible.builtin.copy:
    content: "{{ private_ssh_key_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519"
    group: "users"
    owner: "{{ ansible_user }}"
    mode: 0600 # Only the owner can read and write.
