- name: (lxappearance) install packages
  tags:
    - lxappearance
    - packages
  community.general.pacman:
    name: lxappearance
    state: latest

- name: (lxappearance) copy config files
  become: false
  tags:
    - lxappearance
    - files
  ansible.builtin.command:
    cmd: "cp -rf {{ role_path }}/files/{{ item }} /home/{{ ansible_user }}/"
  loop:
    - .themes
    - .icons

- name: (lxappearance) save config directories
  become: false
  tags:
    - save
    - save-lxappearance
  ansible.builtin.command:
    cmd: "cp -rf /home/{{ ansible_user }}/{{ item }} {{ role_path }}/files/"
  loop:
    - .themes
    - .icons

