- name: (i3lock) Install i3lock
  tags:
    - i3lock
    - packages
  community.general.pacman:
    name: i3lock
    state: latest

- name: (i3lock-fancy) Install i3lock-fancy using yay
  become: false
  tags:
    - i3lock
    - packages
  ansible.builtin.command: yay -S --noconfirm --needed --answerclean None --answerdiff None i3lock-fancy-git
