- name: (themes) copy config files
  become: false
  tags:
    - themes
    - files
  ansible.builtin.command:
    cmd: "cp -rf {{ role_path }}/files/themes /home/{{ ansible_user }}/"

- name: (themes) save config files
  become: false
  tags:
    - save
    - save-themes
  ansible.builtin.command:
    cmd: "cp -rf /home/{{ ansible_user }}/themes {{ role_path }}/files/"
