- name: (rofi) install packages
  tags:
    - rofi
    - packages
  community.general.pacman:
    name: rofi
    state: latest

- name: (rofi) copy config files
  become: false
  tags:
    - rofi
    - files
  ansible.builtin.command:
    cmd: "cp -rf {{ role_path }}/files/rofi /home/{{ ansible_user }}/.config/"

- name: (rofi) make rofi scripts executable
  become: false
  tags:
    - rofi
    - files
  ansible.builtin.shell:
    cmd: "chmod -R +x /home/{{ ansible_user }}/.config/rofi/scripts /home/{{ ansible_user }}/.config/rofi/launchers /home/{{ ansible_user }}/.config/rofi/powermenu /home/{{ ansible_user }}/.config/rofi/applets /home/{{ ansible_user }}/.config/rofi/theme_scripts"

- name: (rofi) save config files
  become: false
  tags:
    - save
    - save-rofi
  ansible.builtin.command:
    cmd: "cp -rf /home/{{ ansible_user }}/.config/rofi {{ role_path }}/files/"
