- name: (alacritty) install packages
  tags:
    - alacritty
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - alacritty

- name: (alacritty) copy config files
  become: false
  tags:
    - alacritty
    - files
  ansible.builtin.copy:
    src: alacritty
    dest: /home/{{ ansible_user }}/.config/
    group: "users"
    owner: "{{ ansible_user }}"
    mode: 0644 # the owner can read and write the file, but other users can only read it

- name: (alacritty) save config files
  become: false
  tags:
    - save
    - save-alacritty
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/alacritty
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/alacritty/files/
    group: "users"
    owner: "{{ ansible_user }}"
    mode: 0644 # the owner can read and write the file, but other users can only read it
