- name: (postgres) Install postgres package
  tags:
    - postgres
    - packages
  community.general.pacman:
    name: postgresql
    state: latest

- name: (postgres) Initialize database cluster
  tags:
    - postgres
    - system
  become_user: postgres
  command: initdb -D /var/lib/postgres/data
  when: not ansible_facts['ansible_stat']['exists']
  register: db_initialized
  ignore_errors: true

- name: (postgres) Check if the database is initialized
  stat:
    path: /var/lib/postgres/data/postgresql.conf
  register: ansible_stat


- name: (postgres) Enable and start PostgreSQL service
  tags:
    - postgres
    - system
  become: yes
  ansible.builtin.systemd:
    name: postgresql
    enabled: yes
    state: started
