- name: (postgres) Install postgres package
  tags:
    - postgres
    - packages
  community.general.pacman:
    name: postgresql
    state: latest

- name: (postgres) Initialize database cluster
  tags:
    - postgres
    - system
  become: yes
  become_user: postgres
  command: initdb --locale=C.UTF-8 -E UTF8 -D /var/lib/postgres/data
  args:
    creates: /var/lib/postgres/data/PG_VERSION
  ignore_errors: true

- name: (postgres) Enable and start PostgreSQL service
  tags:
    - postgres
    - system
  become: yes
  ansible.builtin.systemd:
    name: postgresql
    enabled: yes
    state: started
